# docker-compose.yml
version: "3"
services:
  tht-fulltimeforce:
    # restart: on-failure
    build: .
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/src/
      - /node_modules